name: Deploy to Multi-Cloud

on:
  workflow_dispatch:  
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Ansible  

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Write SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ansible_key
        chmod 600 ansible_key

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i inventory playbook.yml
